export default function DisclaimerPage() {
  return (
    <article className="mx-auto max-w-2xl px-6 py-10 prose prose-slate">
      <h1 className="text-2xl font-semibold tracking-tight">Disclaimer</h1>
      <p className="mt-3 text-slate-700">
        Trade-Idea Critic is provided for educational and research purposes only. It is not
        financial, investment, legal, or tax advice. Nothing it produces should be construed
        as a recommendation to buy, sell, or hold any security.
      </p>
      <p className="mt-3 text-slate-700">
        Market data is sourced from public providers and may be delayed, incomplete, or
        inaccurate. The critique is generated by language models; do not rely on it for
        real-money decisions without independent verification.
      </p>
      <p className="mt-3 text-slate-700">
        Submitted theses are stored for up to 90 days to support the system. The site has
        no analytics, no cookies, and no tracking. Identifiers (request IDs) are random
        UUIDs; we never collect your name, email, or any account information.
      </p>
      <p className="mt-3 text-slate-700">
        You are solely responsible for your trading decisions and their outcomes. By using
        this tool you agree to these terms.
      </p>
    </article>
  );
}
