/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/critique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a thesis for critique
         * @description Queue a critique. Returns the `request_id` the client polls or streams.
         */
        post: operations["submit_critique_api_v1_critique_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/critique/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a critique
         * @description Return the critique body, or a `pending` envelope while work is in flight.
         */
        get: operations["get_critique_api_v1_critique__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/critique/{request_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream critique progress (SSE)
         * @description Emit `status`, `node_started`, `node_completed`, `final` (or `error`) events.
         *
         *     If the run is already finished, a single `final` (or `error`) event is sent
         *     and the stream closes.
         */
        get: operations["stream_critique_api_v1_critique__request_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Phase 1.3 extends `checks` with real DB, Redis, last_llm states.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BaseRateFinding
         * @description Historical hit rate for the closest matching setup bucket.
         */
        BaseRateFinding: {
            /** Bucket */
            bucket?: {
                [key: string]: string | number;
            };
            /** Hit Rate */
            hit_rate: number;
            /** Sample Size */
            sample_size: number;
            /**
             * Setup
             * @enum {string}
             */
            setup: "orb" | "sr_bounce" | "other";
        };
        /**
         * BiasFinding
         * @description One bias the bias detector identified in the thesis.
         */
        BiasFinding: {
            /**
             * Bias
             * @enum {string}
             */
            bias: "anchoring" | "recency" | "confirmation" | "overconfidence" | "revenge";
            /** Explanation */
            explanation: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high";
            /**
             * Span
             * @description The phrase from the thesis that triggered the flag.
             */
            span: string;
        };
        /**
         * CritiquePending
         * @description 200 response from `GET /api/v1/critique/{id}` when work is still in flight.
         */
        CritiquePending: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Status
             * @default pending
             * @constant
             */
            status: "pending";
        };
        /**
         * CritiqueQueued
         * @description 202 response from `POST /api/v1/critique`.
         */
        CritiqueQueued: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
        /**
         * CritiqueRequest
         * @description Submission body for `POST /api/v1/critique`.
         *
         *     `thesis` is free-text English; the parser is responsible for extracting
         *     structured fields. The ticker inside the thesis must carry an exchange
         *     indicator (`AAPL` / `INFY.NS` / `SAP.DE`); parser will fail closed otherwise.
         */
        CritiqueRequest: {
            /** Thesis */
            thesis: string;
        };
        /**
         * CritiqueResponse
         * @description Final critique body. Mirrors what the synthesizer produced and the critic verified.
         */
        CritiqueResponse: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Gap Flags
             * @description Reasons a partial critique is partial; e.g. 'newsapi_unavailable'.
             */
            gap_flags?: string[];
            parsed_thesis?: components["schemas"]["ParsedThesis"] | null;
            /** Raw Thesis */
            raw_thesis: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            sections?: components["schemas"]["CritiqueSections"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial" | "failed";
            /**
             * Verdict
             * @description Top-line characterization. Absent on `failed`.
             */
            verdict?: ("strong" | "marginal" | "weak") | null;
        };
        /**
         * CritiqueSections
         * @description The four-section critique body, plus base-rate context.
         */
        CritiqueSections: {
            /** Base Rates */
            base_rates?: components["schemas"]["BaseRateFinding"][];
            /** Bias */
            bias?: components["schemas"]["BiasFinding"][];
            /** Disconfirming */
            disconfirming?: components["schemas"]["DisconfirmingItem"][];
            mechanics: components["schemas"]["StructureFinding"];
            setup_critique?: components["schemas"]["SetupCritique"] | null;
            /** Stress Test */
            stress_test?: components["schemas"]["StressTestClaim"][];
        };
        /**
         * DisconfirmingItem
         * @description A piece of evidence that runs counter to the thesis.
         */
        DisconfirmingItem: {
            /** Headline */
            headline: string;
            /**
             * Relevance
             * @enum {string}
             */
            relevance: "ticker" | "sector" | "catalyst" | "peer";
            /**
             * Source
             * @description e.g. 'NewsAPI', 'YahooFinance RSS', 'EDGAR'.
             */
            source: string;
            /** Summary */
            summary: string;
            /** Url */
            url?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description `GET /api/v1/health` body.
         */
        HealthResponse: {
            /**
             * Checks
             * @description Per-dependency state: db, redis, last_llm.
             */
            checks?: {
                [key: string]: string;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down";
            /** Version */
            version: string;
        };
        /**
         * ParsedThesis
         * @description Structured form of the user's free-text thesis.
         */
        ParsedThesis: {
            /**
             * Claims
             * @description Verifiable claims for the stress-tester.
             */
            claims?: string[];
            /**
             * Direction
             * @enum {string}
             */
            direction: "long" | "short";
            /** Entry */
            entry?: number | null;
            /**
             * Exchange
             * @enum {string}
             */
            exchange: "US" | "IN" | "DE";
            /**
             * Raw Confidence Words
             * @description Phrases the bias detector pre-scan flagged.
             */
            raw_confidence_words?: string[];
            /**
             * Setup
             * @enum {string}
             */
            setup: "orb" | "sr_bounce" | "other";
            /** Stop */
            stop?: number | null;
            /** Target */
            target?: number | null;
            /** Ticker */
            ticker: string;
            /** Time Horizon */
            time_horizon?: string | null;
        };
        /**
         * SetupCritique
         * @description Output of the setup specialist (ORB / S/R / generic).
         */
        SetupCritique: {
            /**
             * Checks
             * @description Per-rule check rows, each {rule, status, evidence}.
             */
            checks?: {
                [key: string]: string;
            }[];
            /** Narrative */
            narrative: string;
            /**
             * Quality
             * @enum {string}
             */
            quality: "strong" | "marginal" | "weak";
            /**
             * Setup
             * @enum {string}
             */
            setup: "orb" | "sr_bounce" | "other";
        };
        /**
         * StressTestClaim
         * @description One claim from the thesis, with the stress-tester's verdict.
         */
        StressTestClaim: {
            /** Claim */
            claim: string;
            /** Evidence */
            evidence?: string[];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "supported" | "contradicted" | "unverifiable";
        };
        /**
         * StructureFinding
         * @description Output of the structure critic (trade mechanics).
         */
        StructureFinding: {
            /** Atr 14 */
            atr_14?: number | null;
            /** Issues */
            issues?: string[];
            /** Rr Ratio */
            rr_ratio?: number | null;
            /** Sizing Note */
            sizing_note?: string | null;
            /** Stop To Atr Multiple */
            stop_to_atr_multiple?: number | null;
            /**
             * Verdict
             * @description Prose summary of the mechanics critique.
             */
            verdict: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submit_critique_api_v1_critique_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CritiqueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CritiqueQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_critique_api_v1_critique__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CritiqueResponse"] | components["schemas"]["CritiquePending"];
                };
            };
            /** @description Unknown request_id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_critique_api_v1_critique__request_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream. See docs/api/sse-events.md for event types. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Unknown request_id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
